// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StackForge.Infrastructure.Data.Context;

#nullable disable

namespace StackForge.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StackForgeDbContext))]
    [Migration("20260314004128_AddProfiles")]
    partial class AddProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentorProfileStack", b =>
                {
                    b.Property<Guid>("MentorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StacksId")
                        .HasColumnType("uuid");

                    b.HasKey("MentorsId", "StacksId");

                    b.HasIndex("StacksId");

                    b.ToTable("MentorProfileStack");
                });

            modelBuilder.Entity("StackForge.Domain.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StackForge.Domain.Identity.Entities.UserRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectedProfileType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_user_registrations");

                    b.ToTable("user_registrations", (string)null);
                });

            modelBuilder.Entity("StackForge.Domain.Profile.Entities.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_learner");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("learners", (string)null);
                });

            modelBuilder.Entity("StackForge.Domain.Profile.Entities.MentorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_mentor");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("mentors", (string)null);
                });

            modelBuilder.Entity("StackForge.Domain.Stacks.Entities.Stack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_stacks");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("stacks", (string)null);
                });

            modelBuilder.Entity("MentorProfileStack", b =>
                {
                    b.HasOne("StackForge.Domain.Profile.Entities.MentorProfile", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackForge.Domain.Stacks.Entities.Stack", null)
                        .WithMany()
                        .HasForeignKey("StacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackForge.Domain.Profile.Entities.LearnerProfile", b =>
                {
                    b.OwnsOne("StackForge.Domain.Profile.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("last_name");

                            b1.HasKey("LearnerProfileId");

                            b1.ToTable("learners");

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("StackForge.Domain.Profile.Entities.MentorProfile", b =>
                {
                    b.OwnsOne("StackForge.Domain.Profile.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("MentorProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("last_name");

                            b1.HasKey("MentorProfileId");

                            b1.ToTable("mentors");

                            b1.WithOwner()
                                .HasForeignKey("MentorProfileId");
                        });

                    b.OwnsOne("StackForge.Domain.Profile.ValueObjects.Education", "Education", b1 =>
                        {
                            b1.Property<Guid>("MentorProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("ConclusionDate")
                                .HasColumnType("date")
                                .HasColumnName("conclusion_date");

                            b1.Property<string>("CourseName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("course_name");

                            b1.Property<string>("Institution")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("institution");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("MentorProfileId");

                            b1.ToTable("mentors");

                            b1.WithOwner()
                                .HasForeignKey("MentorProfileId");
                        });

                    b.Navigation("Education")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
